### ISSUE TITLE
Can't join to chat thru pidgin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [EionRobb/skype4pidgin#236]
```
What steps will reproduce the problem?
1. Login to skype
2. Add skype account to pidgin (tried via native, dbus and network libs)
3. Add any chat, even already existed in skype.

What is the expected output? What do you see instead?
Expected opening chat window with ability chatting. Instead of it blank tab 
opens with blank roster. Actually I not join to chatroom.

What version of the plugin are you using? On what operating system?
I'm using svn version, revision 664 with last changes 2013-12-12 22:05:04 +0200.

```

Original issue reported on code.google.com by `dmitri...@tech.namecheap.com` on 21 Jan 2014 at 12:41

**Comment by guest73** [comment]
I have exactly the same problem. What is the status of this issue?

**Comment by EionRobb** [comment]
@guest73 which problem are you having? The status of the issue is closed, if you could open a new issue describing your problem that would be a big help :)

**Comment by guest73** [comment]
Thanks for response. Well I guess I'm having a problem due to an old version of the library in the Linux Mint repository (I am currently on Mint XFCE edition, pidgin 2.10.9) which is 20130613+svn660+dfsg-1 but I am not sure about that. In essence I still can't Join chat. All the same behavior as explained by GoogleCodeExporter. Trying to install skype4pidgin from git but got this error
```
i686-pc-linux-gnu-gcc -I/usr/include/libpurple -DPURPLE_PLUGINS -DENABLE_NLS -Wall -pthread `pkg-config --cflags glib-2.0` -I/usr/include -I. -g -march=athlon-xp -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
/bin/sh: 1: i686-pc-linux-gnu-gcc: not found
make: *** [libskype.so] Error 127
```
Do not know what to do next. Wanted to try this plugin so I can use spell-checking with skype.

**Comment by EionRobb** [comment]
@guest73 please open a new issue to continue the discussion there

Also, that's the old skype plugin not the newer skypeweb plugin
