### ISSUE TITLE
Tell the user that a picture was send

### ISSUE THREAD

**Issue by TomTheDragon** [EionRobb/skype4pidgin#357]
I often have the problem that i dont see if someone is trying to send me a picture, because pidgin cant show the ones that are uploaded to the Skype servers most of the time.
But if i know that someone is trying to send me something, i could ask him to send me a link instead.

**Comment by EionRobb** [comment]
Even better would be to get those messages that aren't displaying to display. Can you get a debug log of those picture messages to try and fix up the picture message retrieval?

**Comment by TomTheDragon** [comment]
Remember that one? https://github.com/EionRobb/skype4pidgin/issues/353

**Comment by TomTheDragon** [comment]
I was using the standard skype client on linux today and i notice that this one just shows you a link where you can see the picture, if someone trys to send you something.
I think this would be a good "option" to have in the plugin.

**Comment by dequis** [comment]
The messages sent from the skype windows desktop client version 7.0 seem to lack `url_thumbnail` attribute, instead they have `uri`

```xml
<URIObject content-type='image/jpeg' uri='https://api.asm.skype.com/v1//objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab'>
    <Text>
        To view this shared photo, go to:
        <a href='https://api.asm.skype.com/s/i?0-cus-d4-97d0274214b5e71695916bd2a30e4fab'>
            https://api.asm.skype.com/s/i?0-cus-d4-97d0274214b5e71695916bd2a30e4fab
        </a>
    </Text>
    <meta type='photo' subtype='' originalName='C:\\Users\\Public\\Pictures\\Sample Pictures\\Chrysanthemum.jpg'/>
</URIObject>
```

The provided uri by itself doesn't work, it needs a view appended to it, for example `/views/imgt1` to get the equivalent of thumbnail. So I wrote a patch to request that if `thumbnail_url` is not there.

But there's another problem: the desktop client sends this as soon as the upload starts, not when the image is ready to be displayed. Trying to fetch this url before it's ready results in a 404.

So there's a `/status` endpoint:

https://api.asm.skype.com/v1//objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab/views/imgt1/status

```json
{
    "view_location": "https://nus1-api.asm.skype.com/v1/objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab/views/imgt1",
    "status_location": "https://nus1-api.asm.skype.com/v1/objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab/views/imgt1/status"
}
```

https://nus1-api.asm.skype.com/v1/objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab/views/imgt1/status

```json
{
    "content_length": ​879394,
    "content_full_length": ​879394,
    "view_length": ​0,
    "content_state": "ready",
    "view_state": "in progress",
    "view_location": "https://nus1-api.asm.skype.com/v1/objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab/views/imgt1",
    "status_location": "https://nus1-api.asm.skype.com/v1/objects/0-cus-d4-97d0274214b5e71695916bd2a30e4fab/views/imgt1/status"
}
```

Or while it's still uploading:

```json
{
    "content_length": ​0,
    "content_full_length": ​0,
    "view_length": ​0,
    "content_state": "no content",
    "view_state": "none",
    "view_location": "https://eus1-api.asm.skype.com/v1/objects/0-eus-d5-3922836fe077c32964a8f1610903bf05/views/imgt1",
    "status_location": "https://eus1-api.asm.skype.com/v1/objects/0-eus-d5-3922836fe077c32964a8f1610903bf05/views/imgt1/status"
}
```

Alternatively, lazy solution, as suggested by the previous comment: display the `https://api.asm.skype.com/s/i?<object id>` URL. It's a bit annoying since it requires the user to log in, but way simpler to implement.

**Comment by dequis** [comment]
Why did you close this?

**Comment by TomTheDragon** [comment]
Because the problem seems to be fixed, i never had any problems with pictures since the newest release.
