### ISSUE TITLE
Constant "Failed to get registration token"

### ISSUE THREAD

**Issue by MrPedros** [EionRobb/skype4pidgin#404]
I have an issue with skype4pidgin. I get this error message constantly.
Please help me solve it, I do not want to get back to Skype...
From where can I get a log?

**Comment by EionRobb** [comment]
Unfortunately this is something happening semi-regularly since a few weeks ago when the Skype servers started to become unreliable.

The plan is to add a bit more resiliency to the plugin to attempt to reconnect a few times before giving up, rather than giving up on the first try, but I haven't gotten there yet.

More info going on at https://github.com/EionRobb/skype4pidgin/issues/396

**Comment by MrPedros** [comment]
Okay, thank you for a response.
